### ISSUE TITLE
“关注店铺”任务完成后会卡住，需要手动返回

### ISSUE THREAD

**Issue by liminghao233** [KirisakiAria/cake#10]
一般任务中（不只是关注店铺），有时达到时间后不能自动返回到任务列表，一直提示“一般任务”，需要手动返回

**Comment by KirisakiAria** [comment]
试试最新版本

**Comment by cccrick** [comment]
我刚用的版本，一直在关注和关注，哈哈哈

**Comment by liminghao233** [comment]
> 试试最新版本

关注店铺任务中，任务完成后会一直关注和取消关注，不能返回任务列表

**Comment by KirisakiAria** [comment]
@liminghao233 @Haevil 更了 再试试，如果还不行就直接把93-98行代码注释掉

**Comment by weidadeguodaxia** [comment]
我这也一样，小米9，把99行的backToTaskPage()改为back()就可以了。另外感谢一下KirisakiAria 更新很快，给你点赞。

**Comment by KirisakiAria** [comment]
@weidadeguodaxia 谢谢支持。可能是有些手机型号用id获取控件有些问题，亦或是用了不同的id，改成back()就是直接模拟触发虚拟键盘返回了。根据之前写的脚本的经验，在某些页面这么做可能导致会直接返回到首页。所以就尽量避免了。如果没有这个问题的话那就直接用这个方法即可。

**Comment by liminghao233** [comment]
@KirisakiAria 新版还是会卡在关注店铺后重复弹出“一般任务”。尝试了注释93-98行，以及上面提到了99行改为back()，都还会出现同样的问题。目前解决手段是在卡住时手动返回任务列表。
手机型号：Huawei P10 Plus，系统：EMUI 9.1，京东版本：V9.3.4
瑕不掩瑜，感谢作者回复和更新

**Comment by quarteridm** [comment]
+1,我的手机也会出现这种问题，realmex7pro，coloros7,京东最新版，和4L的问题完全相同，不过还是感谢作者
