### ISSUE TITLE
请问这要怎么用啊？

### ISSUE THREAD

**Issue by huixiangd** [KirisakiAria/cake#3]

**Comment by Asirup** [comment]
下载auto.js用

**Comment by KirisakiAria** [comment]
装个autojs，打开无障碍，给悬浮窗权限。导入脚本，进京东app叠蛋糕页面打开任务列表，点autojs的悬浮窗运行脚本。

**Comment by huixiangd** [comment]
感谢感谢，但是悬浮窗怎么调出来啊？

**Comment by st21a1** [comment]
#1281报错illegally  formed XML syntax

**Comment by KirisakiAria** [comment]
> 感谢感谢，但是悬浮窗怎么调出来啊？

左侧菜单-录制脚本-悬浮窗

**Comment by KirisakiAria** [comment]
> #1281报错illegally formed XML syntax

请问是不是直接复制粘贴的脚本代码？

**Comment by st21a1** [comment]
> > #1281报错illegally formed XML syntax
> 
> 请问是不是直接复制粘贴的脚本代码？

是我搞错了，我把这个js直接下载结果下载的是网页
