### ISSUE TITLE
请问新任务加入会员有没有办法跳过

### ISSUE THREAD

**Issue by laoxipi** [KirisakiAria/cake#5]
请问新任务加入会员有没有办法跳过

**Comment by KirisakiAria** [comment]
[ff24a2f](https://github.com/KirisakiAria/cake/commit/ff24a2fef99ad7638602cf153d1d28620567d61a)
更新了

**Comment by KirisakiAria** [comment]
如果要跳过的话，把313-315行的
`    if (btnIndex != 2) {
      judge()
    }`
删掉，然后手动改btnIndex的值

**Comment by laoxipi** [comment]
> 如果要跳过的话，把313-315行的
> ` if (btnIndex != 2) { judge() }`
> 删掉，然后手动改btnIndex的值

小白，删掉会，改哪个btnIndex值有点懵，查了下有好几个值

**Comment by KirisakiAria** [comment]
> > 如果要跳过的话，把313-315行的
> > ` if (btnIndex != 2) { judge() }`
> > 删掉，然后手动改btnIndex的值
> 
> 小白，删掉会，改哪个btnIndex值有点懵，查了下有好几个值

第三行那个，其实这个btnIndex代表的就是你要在任务页面点击哪一个“去完成”按钮，序号从0开始

**Comment by laoxipi** [comment]
> > > 如果要跳过的话，把313-315行的
> > > ` if (btnIndex != 2) { judge() }`
> > > 删掉，然后手动改btnIndex的值
> > 
> > 
> > 小白，删掉会，改哪个btnIndex值有点懵，查了下有好几个值
> 
> 第三行那个，其实这个btnIndex代表的就是你要在任务页面点击哪一个“去完成”按钮，序号从0开始

懂了，谢谢
