### ISSUE TITLE
时光机的任务列表从哪儿来？

### ISSUE THREAD

**Issue by changer2222** [KirisakiAria/cake#8]
求入口，谢谢！

**Comment by KirisakiAria** [comment]
APP右上角的日历/攻略，进去后在攻略tab页往下拉，寻找时光碎片
________________________________
发件人: changer2222 <notifications@github.com>
发送时间: 2020年11月1日 16:32
收件人: KirisakiAria/stall <stall@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [KirisakiAria/stall] 时光机的任务列表从哪儿来？ (#8)


求入口，谢谢！

―

**Comment by changer2222** [comment]
打开“京东”App--首页搜“热爱时光机”--“启动时光机”进入活动
谢谢了
